---
abstract: 'Plack application to display the status of Gearman job servers'
author:
  - 'Manfred Stock <mstock@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  IO::Socket::INET: 0
  Module::Build: 0.3601
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Gearman-Status
no_index:
  file:
    - perlcritic.rc
requires:
  Carp: 0
  MRO::Compat: 0
  Net::Telnet::Gearman: 0
  Plack::Component: 0
  Plack::Util::Accessor: 0
  Text::MicroTemplate: 0
  Try::Tiny: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/mstock/Plack-App-Gearman-Status.git
version: 0.001000
